version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_app
    command: /bin/bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
      # ローカルと同じディレクトリをマウント
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # バインドではなくdocker内のディレクトリ
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
